export const POPULATE_PRODUCTS = 'POPULATE_PRODUCTS';
export const POPULATE_PRODUCTS_BY_ID = 'POPULATE_PRODUCTS_BY_ID';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_PAGE = 'SET_PAGE';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const ADD_PRODUCT = 'ADD_PRODUCT';
