export const POPULATE_PRODUCTS = 'POPULATE_PRODUCTS';
export const SET_CATEGORY = 'SET_CATEGORY';

export const SET_MAINPAGE = 'SET_MAINPAGE';
export const SET_PRODUCTSPAGE = 'SET_PRODUCTSPAGE';
export const SET_ITEMPAGE = 'SET_ITEMPAGE';
export const SET_ERROR = 'SET_ERROR';